# nixpacks.toml
# Configuration for Railway deployment

[phases.setup]
# Install required system packages
nixPkgs = ["python39", "gcc", "postgresql"]

[phases.install]
# Install Python dependencies
# Use --no-cache-dir to avoid permission issues
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[providers]
# Ensure we're using the Python provider
python = true